### PR TITLE
refactor code to enhance SOLID principles

### PR DESCRIPTION
**Pull request by jkanyi-web**

### CODE REVIEW

**Comment by jkanyi-web** [comment]
Hey guys before tomorrow morning Abu please resolve the conflicts and check to see if the console app works as expected. I think only the repo owner can resolve merge conflicts directly on github

**Comment by AbuTalha3** [comment]
There are con flicts in the branch which cannot be reviewed. Please resolve conflicts and send PR again.

**Comment by AbuTalha3** [comment]
STATUS: APPROVED 😃

In my opinion, your project is complete! There is nothing else to say other than... it's time to merge it :

Highlights
No linter errors ✔️
Descriptive PR ✔️
Correct Github flow ✔️
Good luck! 🎉

**Review by AbuTalha3 — APPROVED** [review]
STATUS: APPROVED 😃

In my opinion, your project is complete! There is nothing else to say other than... it's time to merge it :

Highlights
No linter errors ✔️
Descriptive PR ✔️
Correct Github flow ✔️
Good luck! 🎉

**Pull request merged**
